//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCardSln.Components.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneCardSln.Components.Resource.ViewModelResource", typeof(ViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 一卡通账户用户名最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Card_Account_Length {
            get {
                return ResourceManager.GetString("Card_Account_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一卡通账户名称不能为空 的本地化字符串。
        /// </summary>
        public static string Card_Account_Require {
            get {
                return ResourceManager.GetString("Card_Account_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一卡通号不能为空 的本地化字符串。
        /// </summary>
        public static string Card_Number_Require {
            get {
                return ResourceManager.GetString("Card_Number_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号不能为空 的本地化字符串。
        /// </summary>
        public static string Code_Require {
            get {
                return ResourceManager.GetString("Code_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定要删除的数据 的本地化字符串。
        /// </summary>
        public static string DelByPk_Require {
            get {
                return ResourceManager.GetString("DelByPk_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典编号最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Dict_Code_Length {
            get {
                return ResourceManager.GetString("Dict_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典名称最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Dict_Name_Length {
            get {
                return ResourceManager.GetString("Dict_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典类型不能为空 的本地化字符串。
        /// </summary>
        public static string Dict_Type_Require {
            get {
                return ResourceManager.GetString("Dict_Type_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典类型不能为空 的本地化字符串。
        /// </summary>
        public static string Dict_Type_Require1 {
            get {
                return ResourceManager.GetString("Dict_Type_Require1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典类型编号最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string DictType_Code_Length {
            get {
                return ResourceManager.GetString("DictType_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典类型名称最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string DictType_Name_Length {
            get {
                return ResourceManager.GetString("DictType_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定要修改的数据 的本地化字符串。
        /// </summary>
        public static string Edit_By_Id {
            get {
                return ResourceManager.GetString("Edit_By_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主键id不能为空 的本地化字符串。
        /// </summary>
        public static string GetByPk_Require {
            get {
                return ResourceManager.GetString("GetByPk_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证长度必须在{2}和{1}之间 的本地化字符串。
        /// </summary>
        public static string Idcard_Length {
            get {
                return ResourceManager.GetString("Idcard_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证号格式不正确 的本地化字符串。
        /// </summary>
        public static string Idcard_Regx {
            get {
                return ResourceManager.GetString("Idcard_Regx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证号不能为空 的本地化字符串。
        /// </summary>
        public static string Idcard_Require {
            get {
                return ResourceManager.GetString("Idcard_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证列表不能为空 的本地化字符串。
        /// </summary>
        public static string Idcards_Require {
            get {
                return ResourceManager.GetString("Idcards_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能为空 的本地化字符串。
        /// </summary>
        public static string Name_Require {
            get {
                return ResourceManager.GetString("Name_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不能为空 的本地化字符串。
        /// </summary>
        public static string NewPwd_Require {
            get {
                return ResourceManager.GetString("NewPwd_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认新密码 的本地化字符串。
        /// </summary>
        public static string NewPwd2_Require {
            get {
                return ResourceManager.GetString("NewPwd2_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码不能为空 的本地化字符串。
        /// </summary>
        public static string OldPwd_Require {
            get {
                return ResourceManager.GetString("OldPwd_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Opt_Length {
            get {
                return ResourceManager.GetString("Opt_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号不能为空 的本地化字符串。
        /// </summary>
        public static string Order_Require {
            get {
                return ResourceManager.GetString("Order_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款金额不能为空 的本地化字符串。
        /// </summary>
        public static string Pay_Amount_Require {
            get {
                return ResourceManager.GetString("Pay_Amount_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款来源最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Pay_Src_Length {
            get {
                return ResourceManager.GetString("Pay_Src_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限编号最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Per_Code_Length {
            get {
                return ResourceManager.GetString("Per_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作方法最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Per_Method_Length {
            get {
                return ResourceManager.GetString("Per_Method_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限名称最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Per_Name_Length {
            get {
                return ResourceManager.GetString("Per_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限类别不能为空 的本地化字符串。
        /// </summary>
        public static string Per_Type_Require {
            get {
                return ResourceManager.GetString("Per_Type_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限uri最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Per_Uri_Length {
            get {
                return ResourceManager.GetString("Per_Uri_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号不能为空 的本地化字符串。
        /// </summary>
        public static string Phone_Require {
            get {
                return ResourceManager.GetString("Phone_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码格式不正确，只能是数字、字母和下划线的组合，密码长度必须在6~10个字符之间 的本地化字符串。
        /// </summary>
        public static string Pwd_Regex {
            get {
                return ResourceManager.GetString("Pwd_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        public static string Pwd_Require {
            get {
                return ResourceManager.GetString("Pwd_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退款来源最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Refund_Src_Length {
            get {
                return ResourceManager.GetString("Refund_Src_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码格式不正确 的本地化字符串。
        /// </summary>
        public static string Regex_CellPhone {
            get {
                return ResourceManager.GetString("Regex_CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域编码最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Regioncode_Max {
            get {
                return ResourceManager.GetString("Regioncode_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域编码不能为空 的本地化字符串。
        /// </summary>
        public static string Regioncode_Require {
            get {
                return ResourceManager.GetString("Regioncode_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Remark_Length {
            get {
                return ResourceManager.GetString("Remark_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序号最大为{1}个字符 的本地化字符串。
        /// </summary>
        public static string Sort_Length {
            get {
                return ResourceManager.GetString("Sort_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序号格式不正确，只能输入0~9的字符组合 的本地化字符串。
        /// </summary>
        public static string Sort_Regex {
            get {
                return ResourceManager.GetString("Sort_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序号不能为空 的本地化字符串。
        /// </summary>
        public static string Sort_Require {
            get {
                return ResourceManager.GetString("Sort_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名长度必须在{2}和{1}之间 的本地化字符串。
        /// </summary>
        public static string User_Name_Length {
            get {
                return ResourceManager.GetString("User_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        public static string User_Name_Require {
            get {
                return ResourceManager.GetString("User_Name_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户真实姓名长度必须在{2}和{1}之间 的本地化字符串。
        /// </summary>
        public static string User_TrueName_Length {
            get {
                return ResourceManager.GetString("User_TrueName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户真实姓名不能为空 的本地化字符串。
        /// </summary>
        public static string User_TrueName_Require {
            get {
                return ResourceManager.GetString("User_TrueName_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户id不能为空 的本地化字符串。
        /// </summary>
        public static string UserId_Require {
            get {
                return ResourceManager.GetString("UserId_Require", resourceCulture);
            }
        }
    }
}
